version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    networks:
        - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge
